version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - nlp-network

  backend:
    build:
      context: ./backend
    ports:
      - "8500:8500"
    networks:
      - nlp-network
networks:
  nlp-network:

